export const MUSES_CLIENT_CONTEXT_PROXY_NAME = 'MUSES_CLIENT_CONTEXT_PROXY_NAME';

export const COMMANDS_MUSES = {
  ECOSYSTEM: {
    CREATE: 'MUSES.ECOSYSTEM.CREATE',
    UPDATE: 'MUSES.ECOSYSTEM.UPDATE',
    DISABLE: 'MUSES.ECOSYSTEM.DISABLE',
    LIST: 'MUSES.ECOSYSTEM.LIST',
    GET: 'MUSES.ECOSYSTEM.GET',
  },
  PROJECT: {
    CREATE: 'MUSES.PROJECT.CREATE',
    UPDATE: 'MUSES.PROJECT.UPDATE',
    DISABLE: 'MUSES.PROJECT.DISABLE',
    LIST: 'MUSES.PROJECT.LIST',
    GET: 'MUSES.PROJECT.GET',
  },
  MODULE: {
    CREATE: 'MUSES.MODULE.CREATE',
    UPDATE: 'MUSES.MODULE.UPDATE',
    DISABLE: 'MUSES.MODULE.DISABLE',
    LIST: 'MUSES.MODULE.LIST',
    GET: 'MUSES.MODULE.GET',
  },
  SUB_MODULE: {
    CREATE: 'MUSES.SUB.MODULE.CREATE',
    UPDATE: 'MUSES.SUB.MODULE.UPDATE',
    DISABLE: 'MUSES.SUB.MODULE.DISABLE',
    LIST: 'MUSES.SUB.MODULE.LIST',
    GET: 'MUSES.SUB.MODULE.GET',
  },
  RESOURCE: {
    CREATE: 'MUSES.RESOURCE.CREATE',
    UPDATE: 'MUSES.RESOURCE.UPDATE',
    DISABLE: 'MUSES.RESOURCE.DISABLE',
    LIST: 'MUSES.RESOURCE.LIST',
    GET: 'MUSES.RESOURCE.GET',
  },
  ACTION: {
    CREATE: 'MUSES.ACTION.CREATE',
    UPDATE: 'MUSES.ACTION.UPDATE',
    DISABLE: 'MUSES.ACTION.DISABLE',
    LIST: 'MUSES.ACTION.LIST',
    GET: 'MUSES.ACTION.GET',
  },
  ACTION_CATALOG: {
    CREATE: 'MUSES.ACTION.CATALOG.CREATE',
    UPDATE: 'MUSES.ACTION.CATALOG.UPDATE',
    DISABLE: 'MUSES.ACTION.CATALOG.DISABLE',
    LIST: 'MUSES.ACTION.CATALOG.LIST',
    GET: 'MUSES.ACTION.CATALOG.GET',
  },
};
